#version 460 core
layout(local_size_x = 8, local_size_y = 4, local_size_z = 1) in;

layout(rgba32f, binding = 0) uniform image2DArray outSignals;

void storeSignal(int layer, ivec2 fragpos, vec4 color) {
    imageStore(outSignals, ivec3(fragpos.xy, layer), color);
}

vec4 loadSingal(int layer, ivec2 fragpos)
{
    return imageLoad(outSignals, ivec3(fragpos.xy, layer));
}

const int SIGNAL_DIRECT   = 0;
const int SIGNAL_INDIRECT = 1;
const int SIGNAL_SPECULAR = 2;
const int SIGNAL_SPEC_IND = 3;
const int SIGNAL_EMISSION = 4;
const int SIGNAL_NOISE    = 5;
//const int SIGNAL_DENOISE  = 6;

layout(rgba32f, binding = 1) uniform image2D denoiseTex;
// do combine pass in here for now

// uniforms
uniform sampler2D gNormal;
uniform sampler2D gAlbedoSpec;
uniform sampler2D depthMap; // use this later for denoising, also take normal
uniform bool doDenoise;
float alphavalue = 1.0f;
uniform int minRadius;

float linearizeDepth(float depth, float NearPlane, float FarPlane)
{
	return (2.0 * NearPlane * FarPlane) / (FarPlane + NearPlane - (depth * 2.0 - 1.0) * (FarPlane - NearPlane));
}

void DenoisePrimary(int radius, float depthLinearized, vec3 currentNormal, const ivec2 pixelCoords, const ivec2 size,
out vec3 directOut, out vec3 specularOut, float depthThershold, float normalThreshold)
{
    vec3 directAccumulated = vec3(0.0f);
    vec3 specularAccumulated = vec3(0.0f);
    float weight = 0.0f;

    for (int x = -radius; x < radius; x++)
    {
            for (int y = -radius; y < radius; y++)
            {
                ivec2 neighbourCoords = pixelCoords + ivec2(x, y);
                neighbourCoords = clamp(neighbourCoords, ivec2(0, 0), size - 1);

                vec4 neighbourDirectColour = loadSingal(SIGNAL_DIRECT, neighbourCoords);
                vec4 neighbourSpecularColour = loadSingal(SIGNAL_SPECULAR, neighbourCoords);
                float neighbourNoise = loadSingal(SIGNAL_NOISE, neighbourCoords).r;

                // simular depth check 
                    

                vec2 neighbourDepthUV = vec2(neighbourCoords) / vec2(size);
                float neighbourDepth = texture(depthMap, neighbourDepthUV).r;
                float neighbourDepthLinearized = linearizeDepth(neighbourDepth, 0.1f, 100.0f);
                // exclude if depth difference is too big
                float depthDifference = abs(neighbourDepthLinearized - depthLinearized);
                if (depthDifference > depthThershold) continue;

                vec3 neighbourNormal = texture(gNormal, neighbourDepthUV).rgb;
                float normalSimilarity = dot(neighbourNormal, currentNormal);
                if (normalSimilarity < normalThreshold) continue;

                float w = 1.0f - neighbourNoise;
                w = max(w * w, 0.0001f);

                directAccumulated += neighbourDirectColour.rgb * w;
                specularAccumulated += neighbourSpecularColour.rgb * w;
                weight += w;
            }
    }
    vec4 directColour = loadSingal(SIGNAL_DIRECT, pixelCoords);
    directOut = (weight > 0.0001f) ? (directAccumulated / weight) : directColour.rgb;

    vec4 specularColour = loadSingal(SIGNAL_SPECULAR, pixelCoords);
    specularOut = (weight > 0.0001f) ? (specularAccumulated / weight) : specularColour.rgb;
}

void PrimarySecondaryDenoise(int radius, float depthLinearized, vec3 currentNormal, const ivec2 pixelCoords,
const ivec2 size, out vec3 indirectOut, out vec3 specularIndirectOut, float depthThershold, float normalThreshold)
{
    vec3 indirectAccumulated = vec3(0.0f);
    vec3 specularIndirectAccumulated = vec3(0.0f);
    float weight = 0.0f;

    for (int x = -radius; x < radius; x++)
    {
            for (int y = -radius; y < radius; y++)
            {
                ivec2 neighbourCoords = pixelCoords + ivec2(x, y);
                neighbourCoords = clamp(neighbourCoords, ivec2(0, 0), size - 1);

                vec4 neighbourIndirectColour = loadSingal(SIGNAL_INDIRECT, neighbourCoords);
                vec4 neighbourSpecularIndirectColour = loadSingal(SIGNAL_SPEC_IND, neighbourCoords);
                float neighbourNoise = loadSingal(SIGNAL_NOISE, neighbourCoords).r;

                // simular depth check 
                vec2 neighbourDepthUV = vec2(neighbourCoords) / vec2(size);
                float neighbourDepth = texture(depthMap, neighbourDepthUV).r;
                float neighbourDepthLinearized = linearizeDepth(neighbourDepth, 0.1f, 100.0f);
                // exclude if depth difference is too big
                float depthDifference = abs(neighbourDepthLinearized - depthLinearized);
                if (depthDifference > depthThershold) continue;

                vec3 neighbourNormal = texture(gNormal, neighbourDepthUV).rgb;
                float normalSimilarity = dot(neighbourNormal, currentNormal);
                if (normalSimilarity < normalThreshold) continue;

                float w = 1.0f - neighbourNoise;
                w = max(w * w, 0.0001f);

                indirectAccumulated += neighbourIndirectColour.rgb * w;
                specularIndirectAccumulated += neighbourSpecularIndirectColour.rgb * w;
                weight += w;
            }
    }

    vec4 indirectColour = loadSingal(SIGNAL_INDIRECT, pixelCoords);
    indirectOut = (weight > 0.0001f) ? (indirectAccumulated / weight) : indirectColour.rgb;

    vec4 specularIndirectColour = loadSingal(SIGNAL_SPEC_IND, pixelCoords);
    specularIndirectOut = (weight > 0.0001f) ? (specularIndirectAccumulated / weight) : specularIndirectColour.rgb;
}

void denoiseIndirect(int radius, int secondaryRadius, float depthLinearized, vec3 currentNormal,
                     const ivec2 pixelCoords, const ivec2 size, out vec3 indirectOut, out vec3 specularIndirectOut,
                     float depthThershold, float normalThreshold)
{

    vec3 nindirectColour = vec3(0.0f);
    vec3 nindirectSpecularColour = vec3(0.0f);

    float noise = loadSingal(SIGNAL_NOISE, pixelCoords).r;
    if (noise != 0.0f) // noise cant sample, skip
    {

        PrimarySecondaryDenoise(radius, depthLinearized, currentNormal, pixelCoords, size, nindirectColour, nindirectSpecularColour, depthThershold, normalThreshold);
        indirectOut = nindirectColour;
        specularIndirectOut = nindirectSpecularColour;
        return;
    }

    nindirectColour = loadSingal(SIGNAL_INDIRECT, pixelCoords).rgb;
    nindirectSpecularColour = loadSingal(SIGNAL_SPEC_IND, pixelCoords).rgb;

    vec3 weights = vec3(0.2126, 0.7152, 0.0722);
    float currentLumanance = dot(nindirectColour / 255.0, weights);
    float currentSLumanance = dot(nindirectSpecularColour / 255.0, weights);

    float totalLuminance = 0.0f;
    float totalSLuminance = 0.0f;
    int validSamples = 0;

    for (int x = -secondaryRadius; x < secondaryRadius; x++)
    {
            for (int y = -secondaryRadius; y < secondaryRadius; y++)
            {
                ivec2 neighbourCoords = pixelCoords + ivec2(x, y);
                neighbourCoords = clamp(neighbourCoords, ivec2(0, 0), size - 1);

                // load raw indirect colours
                vec4 neighbourIndirectColour = loadSingal(SIGNAL_INDIRECT, neighbourCoords);
                vec4 neighbourSpecularIndirectColour = loadSingal(SIGNAL_SPEC_IND, neighbourCoords);
                float neighbourNoise = loadSingal(SIGNAL_NOISE, neighbourCoords).r;

                vec2 neighbourDepthUV = vec2(neighbourCoords) / vec2(size);
                float neighbourDepth = texture(depthMap, neighbourDepthUV).r;
                float neighbourDepthLinearized = linearizeDepth(neighbourDepth, 0.1f, 100.0f);
                // exclude if depth difference is too big
                float depthDifference = abs(neighbourDepthLinearized - depthLinearized);
                if (depthDifference > depthThershold) continue;

                vec3 neighbourNormal = texture(gNormal, neighbourDepthUV).rgb;
                float normalSimilarity = dot(neighbourNormal, currentNormal);
                if (normalSimilarity < normalThreshold) continue;

                if (neighbourNoise != 0.0f) // noise cant sample, skip
                    continue;


                vec3 weights = vec3(0.2126, 0.7152, 0.0722);
                float luminance = dot(neighbourIndirectColour.rgb / 255.0, weights);
                float sLuminance = dot(neighbourSpecularIndirectColour.rgb / 255.0, weights);

                totalLuminance += luminance;
                totalSLuminance += sLuminance;
                validSamples++;
            }
            float avgLuminance = (validSamples > 0) ? (totalLuminance / float(validSamples)) : 0.0f;
            float avgsLuminance = (validSamples > 0) ? (totalSLuminance / float(validSamples)) : 0.0f;

            indirectOut = nindirectColour * (avgLuminance / max(currentLumanance, 0.0001f));
            specularIndirectOut = nindirectSpecularColour * (avgsLuminance / max(currentSLumanance, 0.0001f));
    }
}

void main() {
    // Intentionally does nothing
    const ivec2 pixelCoords = ivec2(gl_GlobalInvocationID.xy);

    const ivec2 size = imageSize(outSignals).xy; // size of screen

    // return if off screen
    if (pixelCoords.x >= size.x || pixelCoords.y >= size.y) return;

    const ivec2 albedosize = textureSize(gAlbedoSpec, 0);
    vec2 albedoUV = vec2(pixelCoords) / vec2(size);
    vec3 albedoTex = texture(gAlbedoSpec, albedoUV).rgb;
    float specTex = texture(gAlbedoSpec, albedoUV).a;

    float reflectionSmoothness = 0.5f;
    //    float depth = texture(depthMap, depthUV).r;

    // combine all signals for early skip
    vec3 directSignal = loadSingal(SIGNAL_DIRECT, pixelCoords).rgb;
    vec3 indirectSignal = loadSingal(SIGNAL_INDIRECT, pixelCoords).rgb;
    vec3 specularSignal = loadSingal(SIGNAL_SPECULAR, pixelCoords).rgb;
    vec3 specularIndirectSignal = loadSingal(SIGNAL_SPEC_IND, pixelCoords).rgb;
    vec3 emissionSignal = loadSingal(SIGNAL_EMISSION, pixelCoords).rgb;

    //vec4 signalCombined = vec4( albedoTex * (directSignal) + (specularSignal * reflectionSmoothness) + emissionSignal, 1.0f);
    
    vec4 signalCombined = vec4( albedoTex * (directSignal + indirectSignal) + 
    ( (specularSignal + specularIndirectSignal) * reflectionSmoothness) + emissionSignal, 1.0f);
    
    //vec4 signalCombined = vec4(specularIndirectSignal, 1.0f);

    //vec4 signalCombined = vec4(indirectSignal, 1.0f); // indirect
    //vec4 signalCombined = vec4(indirectSignal + directSignal, 1.0f); // GI
    float isNoisy = loadSingal(SIGNAL_NOISE, pixelCoords).r;

    //if (colour.a < 0.1f)
    //{
    //    imageStore(denoiseTex, pixelCoords, vec4(0.0f));
    //    return;
    //}

    // if denosing is turned off
    //if (pixelCoords.x < size.x * 0.5f ){
    if (!doDenoise) {
    imageStore(denoiseTex, pixelCoords, vec4(signalCombined.xyz, alphavalue));
    //storeSignal(SIGNAL_DENOISE, pixelCoords, vec4(signalCombined.xyz, alphavalue));
    //SIGNAL_DENOISE
    //imageStore(denoiseTex, pixelCoords, vec4(vec3(isNoisy), alphavalue)); 
    return;
    }

    // if there is like no noise
    bool primaryskip = (isNoisy == 0.0f);
    //imageStore(denoiseTex, pixelCoords, vec4(signalCombined.xyz, alphavalue)); 
    //storeSignal(SIGNAL_DENOISE, pixelCoords, vec4(signalCombined.xyz, alphavalue));
    //return; 

    const ivec2 depthsize = textureSize(depthMap, 0);
    vec2 depthUV = vec2(pixelCoords) / vec2(size);
    float depth = texture(depthMap, depthUV).r;
    float depthLinearized = linearizeDepth(depth, 0.1f, 100.0f);
    vec3 currentNormal = texture(gNormal, depthUV).rgb;

    float depthThershold = 0.1f;
    float normalThreshold = 0.9f;

    float dencity = 0.0f;
    if (!primaryskip)
    {
        // do a dencity check here
        for (int x = -2; x < 2; x++)
        {
                for (int y = -2; y < 2; y++)
                {
                    ivec2 neighbourCoords = pixelCoords + ivec2(x, y);
                    neighbourCoords = clamp(neighbourCoords, ivec2(0, 0), size - 1);
                    float neighbourNoise = loadSingal(SIGNAL_NOISE, neighbourCoords).r;

                    vec2 neighbourDepthUV = vec2(neighbourCoords) / vec2(size);
                    float neighbourDepth = texture(depthMap, neighbourDepthUV).r;
                    float neighbourDepthLinearized = linearizeDepth(neighbourDepth, 0.1f, 100.0f);
                    // exclude if depth difference is too big
                    float depthDifference = abs(neighbourDepthLinearized - depthLinearized);
                    if (depthDifference > depthThershold) continue;

                    vec3 neighbourNormal = texture(gNormal, neighbourDepthUV).rgb;
                    float normalSimilarity = dot(neighbourNormal, currentNormal);
                    if (normalSimilarity < normalThreshold) continue;

                    dencity += neighbourNoise;
                }
        }
    }
    vec3 accumulated = vec3(0.0f);
    float weight = 0.0f;

    float rawDensity = dencity / 2;

    float maxRadius = 50.0f;

    float newRadius = clamp(rawDensity + minRadius, minRadius, maxRadius);

    float smoothRadius = newRadius;

    // final equaision should be albedo * GI + specular + emissive
    vec3 direct = vec3(0.0f);
    vec3 specular = vec3(0.0f);

    if (!primaryskip) DenoisePrimary(int(smoothRadius), depthLinearized, currentNormal, pixelCoords, size, direct, specular, depthThershold, normalThreshold);

    vec3 indirect = vec3(0.0f);
    vec3 specularIndirect = vec3(0.0f);


    int lumaRadius = 5;
    denoiseIndirect(int(smoothRadius), lumaRadius, depthLinearized, currentNormal, pixelCoords, size, indirect, specularIndirect, depthThershold, normalThreshold);

    vec3 emission = vec3(0.0f);
    vec3 final = vec3(0.0f);
    //vec3 final = specularIndirect;
    //vec3 final = direct; // * albedoTex;

    if (primaryskip)
    {
        final = albedoTex * (directSignal + indirect) + (specularSignal + specularIndirect) + emission;
    }
    else
    {
        final = albedoTex * (direct + indirect) + (specular + specularIndirect) + emission;
    }

    //vec3 final = (indirect + direct); // gi
    //vec3 final = (indirect);

    // equivalent to fragcolour 
    imageStore(denoiseTex, pixelCoords, vec4(final, alphavalue));
    //storeSignal(SIGNAL_DENOISE, pixelCoords, vec4(final, alphavalue));
}