#version 460 core
layout(local_size_x = 8, local_size_y = 4, local_size_z = 1) in;

layout(rgba32f, binding = 0) uniform image2D raytracedTex;
layout(rgba32f, binding = 1) uniform image2D denoiseTex;
layout(rgba32f, binding = 2) uniform image2D NoiseMask;

// uniforms
uniform sampler2D depthMap; // use this later for denoising, also take normal
uniform bool doDenoise;
float alphavalue = 0.3f;
uniform int minRadius;

void main() {
    // Intentionally does nothing
    const ivec2 pixelCoords = ivec2(gl_GlobalInvocationID.xy);

    const ivec2 size = imageSize(denoiseTex); // size of screen

    // return if off screen
    if (pixelCoords.x >= size.x || pixelCoords.y >= size.y) return;

    vec4 colour = imageLoad(raytracedTex, pixelCoords);
    float isNoisy = imageLoad(NoiseMask, pixelCoords).r;

    if (colour.a < 0.1f)
    {
        imageStore(denoiseTex, pixelCoords, vec4(0.0f));
        return;
    }

    // if denosing is turned off
    //if (pixelCoords.x < size.x * 0.5f ){
    if (!doDenoise) {
    imageStore(denoiseTex, pixelCoords, vec4(colour.xyz, alphavalue)); 
    //imageStore(denoiseTex, pixelCoords, vec4(vec3(isNoisy), alphavalue)); 
    return;
    }

    // if there is like no noise
    if (isNoisy == 0.0f ) {
    imageStore(denoiseTex, pixelCoords, vec4(colour.xyz, alphavalue)); 
    return; 
    }

    float dencity = 0.0f;
    // do a dencity check here
    for (int x = -2; x < 2; x++)
    {
            for (int y = -2; y < 2; y++)
            {
                ivec2 neighbourCoords = pixelCoords + ivec2(x, y);
                neighbourCoords = clamp(neighbourCoords, ivec2(0, 0), size - 1);
                float neighbourNoise = imageLoad(NoiseMask, neighbourCoords).r;

                float neighbourColouralpha = imageLoad(raytracedTex, neighbourCoords).a;
                if (neighbourColouralpha < 0.1f)
                continue;

                dencity += neighbourNoise;
            }
    }
    vec3 accumulated = vec3(0.0f);
    float weight = 0.0f;

    float rawDensity = dencity / 2;

    float maxRadius = 30.0f;

    float newRadius = clamp(rawDensity + minRadius, minRadius, maxRadius);

    float smoothRadius = newRadius;

    for (int x = -int(smoothRadius); x < int(smoothRadius); x++)
    {
            for (int y = -int(smoothRadius); y < int(smoothRadius); y++)
            {
                ivec2 neighbourCoords = pixelCoords + ivec2(x, y);
                neighbourCoords = clamp(neighbourCoords, ivec2(0, 0), size - 1);

                vec4 neighbourColour = imageLoad(raytracedTex, neighbourCoords);
                float neighbourNoise = imageLoad(NoiseMask, neighbourCoords).r;

                //if (neighbourColour.a < 0.1f)
                //continue;


                float w = 1.0f - neighbourNoise;
                w = max(w * w, 0.0001f);

                accumulated += neighbourColour.rgb * w;
                weight += w;
            }
    }
    vec3 finalColour = (weight > 0.0001f) ? (accumulated / weight) : colour.rgb;

    // equivalent to fragcolour 
    imageStore(denoiseTex, pixelCoords, vec4(finalColour, alphavalue));
}