#version 460 core

#extension GL_ARB_gpu_shader_int64 : enable
#extension GL_ARB_bindless_texture : require
//#extension GL_EXT_ray_query : enable

layout(local_size_x = 8, local_size_y = 4, local_size_z = 1) in;

layout(rgba32f, binding = 0) uniform image2DArray outSignals;

void storeSignal(int layer, ivec2 fragpos, vec4 color) {
    imageStore(outSignals, ivec3(fragpos.xy, layer), color);
}

vec4 loadSingal(int layer, ivec2 fragpos)
{
    return imageLoad(outSignals, ivec3(fragpos.xy, layer));
}

const int SIGNAL_DIRECT   = 0;
const int SIGNAL_INDIRECT = 1;
const int SIGNAL_SPECULAR = 2;
const int SIGNAL_SPEC_IND = 3;
const int SIGNAL_EMISSION = 4;
const int SIGNAL_NOISE    = 5;

uniform sampler2D depthMap;

struct triangle // need 16 byte allignment
{
    // position
    vec4 a, b, c;
    // texUV
    vec4 aTex; // 16 bytes
    vec4 bTex; // 16 bytes
    vec4 cTex; // 16 bytes
    // normal
    vec4 aNormal, bNormal, cNormal;
    // tangents
    vec4 aTangent, bTangent, cTangent;
    // bitangants
    vec4 aBiTangent, bBiTangent,  cBiTangent;
};

struct rayMesh
{
	int triangleCount; // 4
	int meshIndex; // 4
    int modelIndex;
    int materialIndex;

    uint64_t instanceUUID;
    uint64_t meshUUID;

    // add 3 handles for each texture 
    uint64_t albedoHandle;
    uint64_t specularHandle;
    uint64_t normalHandle;

};

struct modelQuickData
{
    uint64_t instanceUUID;
    uint64_t padding;
    mat4 ModelMatrix;
    mat4 NormalMatrix;
    vec4 uvScale;
};

struct rootnodeAABB
{
    vec4 position;
    vec4 scale;

    uint64_t instanceUUID;
	uint64_t padding;
};

layout(std430, binding = 7) buffer TriangleBuffer {
    triangle triangles[];
};
layout(std430, binding = 8) buffer MeshBuffer {
    rayMesh meshes[];
};
layout(std430, binding = 9) buffer QuickBuffer {
    modelQuickData quickModels[];
};
layout(std430, binding = 10) buffer RootAABBBuffer {
    rootnodeAABB rootAABBs[];
};
// uniforms

#define INF 3.40282347e+38f

uniform mat4 u_ViewMatrix;
uniform mat4 u_ProjectionMatrix;
uniform vec3 cameraPosition;
uniform float time;
uniform float deltatime;
uniform bool cameraMoved;

uniform float maxDistance;
uniform float noiseThreshold;
uniform float reflectionDistance;
uniform int reflectionBounces;
uniform vec3 skycolour;
uniform bool doAccumulate;
uniform int MaxAccumulatedFrames;
uniform sampler2D BlueNoiseTex;
//uniform samplerCube skybox; 
uniform int frameCount;

uniform vec3 directLightPos;
uniform vec3 directLightCol;
uniform bool doDirLight;

uniform int indirectBounces;
uniform int indirectSamples;

uniform vec3 sceneBoundPos;
uniform vec3 sceneBoundScale;

uniform uint64_t skyboxHandle;

//vec3 skycolour = vec3(0.0f);

// aabb

// hit result struct

struct hitResult
{
    bool hit;
    vec3 normal;
    vec3 lasthit;
    float hitDistance;
    vec4 colour;
    vec2 uv;
    vec2 uvScale;
    vec3 lightNormal;
    int meshIndex;
    uint64_t hitInstanceUUID;

    mat3 TBN;
    vec3 T;
    vec3 B;
};

struct Light
{
	vec3 position;
	vec3 rotation;
	vec3 colour;
	float radius;
	int type;
};

uniform Light Lights[64]; // should replace with ssbo later down the line 

uniform int lightCount;

float rand(vec2 co){
    return fract(sin(dot(co.xy ,vec2(12.9898, 78.233))) * 43758.5453);
}

float linearizeDepth(float depth, float NearPlane, float FarPlane)
{
	return (2.0 * NearPlane * FarPlane) / (FarPlane + NearPlane - (depth * 2.0 - 1.0) * (FarPlane - NearPlane));
}

vec3 transformPoint(vec3 p, mat4 matrix)
{
    vec4 transformed = matrix * vec4(p, 1.0f);
    return vec3(transformed);
}

hitResult AabbVsRay(vec3 rayOrigin, vec3 rayDir, vec3 position, vec3 scale)
{
    hitResult hr; hr.hit = false; hr.hitDistance = INF;
	vec3 Min = position - scale;
	vec3 Max = position + scale;

	// inverted direction
	vec3 invDir = 1.0f / rayDir;

	// calc intersection distances for each axis
	vec3 t0 = (Min - rayOrigin) * invDir;
	vec3 t1 = (Max - rayOrigin) * invDir;

	// mae sure tmin is the entry point, tmax is the exit point for each axis
	vec3 tMin = min(t0, t1);
	vec3 tMax = max(t0, t1);

	// find entry and exit tvalues for the ray
	float tNear = max( max(tMin.x, tMin.y), tMin.z );
	float tFar = min( min(tMax.x, tMax.y), tMax.z );

	// near > far = misses the box
	// far < 0 = behind the box
    // far > max_distance = out of distance

	if (tNear > tFar || tFar < 0) {return hr;}
    hr.hit = true;
    hr.hitDistance = tNear;
    return hr;
}

// barycentric

float areaOfTriangle(vec3 a, vec3 b, vec3 c)
{
    // 2 vectors from points
    vec3 u = b - a;
    vec3 v = c - a;

    // cross product of u and v
    vec3 cp = cross(u, v);

    // return half of magnitue of the vector "cp"
    return length(cp) * 0.5;

}


// trianglevsray
hitResult triangleVsRay(vec3 rayOrigin, vec3 rayDir, triangle vertice, float maxDist)
{
    hitResult data;
    data.hit = false;
    data.lasthit = vec3(0.0f);
    data.hitDistance = 0.0f;

    vec3 normal = normalize(cross(vertice.b.xyz - vertice.a.xyz, vertice.c.xyz - vertice.a.xyz));

    if (dot(normal, rayDir) > 0.0f) {
    normal = -normal;}

    data.normal = normal;


    // check if ray is parallel to triangle
	float dotProduct = dot(normal, rayDir);
	if (abs(dotProduct) < 0.0001f) return data;

    	// Find the distance 't' to the plane
	float t = dot(vertice.a.xyz - rayOrigin, normal) / dotProduct;

	// if t is negative, the triangle is behind the ray, also if past max distance disgard
	if (t < 0 || t > maxDist) return data;

	// Find the intersection point
	vec3 p = rayOrigin + (t * rayDir);

    // triangle in point collision

    float totalarea = areaOfTriangle(vertice.a.xyz,vertice.b.xyz,vertice.c.xyz);
	// calculate area of sub-triangles
	float areaPAB = areaOfTriangle(p, vertice.a.xyz, vertice.b.xyz);
	float areaPBC = areaOfTriangle(p, vertice.b.xyz, vertice.c.xyz);
	float areaPCA = areaOfTriangle(p, vertice.c.xyz, vertice.a.xyz);

    //  
    float weightA = areaPBC / totalarea;
    float weightB = areaPCA / totalarea;
    float weightC = areaPAB / totalarea;

    float areasum = areaPAB + areaPBC + areaPCA;
    float relativeEpsilon = 0.0001f * totalarea;

	// Check if the intersection point is inside the triangle
	if (abs(totalarea - areasum) < relativeEpsilon)
	{
		data.hit = true;
		data.lasthit = p;
		data.hitDistance = t;
        data.uv = (weightA  * vertice.aTex.xy) + (weightB *  vertice.bTex.xy) + (weightC * vertice.cTex.xy); 

        vec3 interpN = (weightA * vertice.aNormal.xyz) + 
                    (weightB * vertice.bNormal.xyz) + 
                    (weightC * vertice.cNormal.xyz);

        vec3 interpT = (weightA * vertice.aTangent.xyz) + 
                   (weightB * vertice.bTangent.xyz) + 
                   (weightC * vertice.cTangent.xyz);

        vec3 interpB = (weightA * vertice.aBiTangent.xyz) + 
                   (weightB * vertice.bBiTangent.xyz) + 
                   (weightC * vertice.cBiTangent.xyz);

        data.lightNormal = normalize(interpN);
        data.T = normalize(interpT);
        data.B = normalize(interpB);

        if (dot(data.normal, data.lightNormal) < 0.0f) {
        data.lightNormal = -data.lightNormal;
        data.T = -data.T;
        data.B = -data.B;
        
        //data.TBN = mat3(data.T, data.B, data.lightNormal);
        }
	}

    return data;
}

vec3 rayDirfromCam(mat4 projection, mat4 view, ivec2 pixelCoords, ivec2 size)
{
    // uv
    vec2 uv = (vec2(pixelCoords) + 0.5) / vec2(size) * 2.0 - 1.0;
    vec4 target = projection * vec4(uv.x, uv.y, -1.0, 1.0);
    vec3 rayDirView = normalize(target.xyz / target.w);
    vec3 rayDirWorld = normalize(mat3(view) * rayDirView);

    return normalize(rayDirWorld);
}


hitResult simpleTrace(vec3 rayOrigin, vec3 rayDir, float maxDist)
{
    hitResult finalhit; finalhit.hit = false; finalhit.hitDistance = INF; finalhit.lasthit;

    for (int i = 0; i < triangles.length(); i++)
    {
            hitResult HR = triangleVsRay(rayOrigin, rayDir, triangles[i], maxDist); //max_distance
            
            if (HR.hit)
            {
                if (HR.hitDistance < finalhit.hitDistance)
                {
                finalhit = HR;
                finalhit.colour = vec4(triangles[i].a.w, triangles[i].b.w, triangles[i].c.w, 1.0f);
                } // close dis
            }
    }

    return finalhit;
}

hitResult BreadPhaseSceneTrace(vec3 rayOrigin, vec3 rayDir, float maxDist)
{
    hitResult finalhit; 
    finalhit.hit = false; 
    finalhit.hitDistance = maxDist; 

    mat4 currentMatrix = mat4(1.0f);
    mat4 currentNormalMatrix = mat4(1.0f);
    vec2 currentUvScale = vec2(0.0f);
    vec3 rootPos = vec3(0.0f);
    vec3 rootScale = vec3(0.0f);

    int triOffset = 0; 
    	// sceneBoundPos sceneBoundScale

    // inital scene bounds
    hitResult sceneHR = AabbVsRay(rayOrigin, rayDir, sceneBoundPos, sceneBoundScale);
    if (sceneHR.hit){

    for (int i = 0; i < meshes.length(); i++)
    {
        // root nodes
        rootPos = rootAABBs[i].position.xyz;
        rootScale = rootAABBs[i].scale.xyz;

        // find model matrix from quick data
        for (int m = 0; m < quickModels.length(); m++)
        {
        // id check 
            if (meshes[i].instanceUUID == quickModels[m].instanceUUID)
            {
                currentMatrix = quickModels[m].ModelMatrix;
                currentNormalMatrix = quickModels[m].NormalMatrix;
                currentUvScale = quickModels[m].uvScale.xy;
                break;
            }
        }
        // aabb test
        hitResult boxHR = AabbVsRay(rayOrigin, rayDir, rootPos, rootScale);
       // if hit test triangles
        if (boxHR.hit && boxHR.hitDistance < finalhit.hitDistance)
        {
            int start = triOffset;
            int end = triOffset + meshes[i].triangleCount;

            for (int t = start; t < end; t++)
            {
                triangle newtri = triangles[t];
                newtri.a.xyz = transformPoint(triangles[t].a.xyz, currentMatrix);
                newtri.b.xyz = transformPoint(triangles[t].b.xyz, currentMatrix);
                newtri.c.xyz = transformPoint(triangles[t].c.xyz, currentMatrix);

                hitResult triHit = triangleVsRay(rayOrigin, rayDir, newtri, maxDist);
                
                if (triHit.hit && triHit.hitDistance < finalhit.hitDistance)
                {
                        float albedoAlpha = 1.0f;
                        if (meshes[i].albedoHandle != 0)
                        {
                            sampler2D albedoSampler = sampler2D(meshes[i].albedoHandle); 
                            albedoAlpha = texture(albedoSampler, triHit.uv * currentUvScale).a; // uvScale
                        }

                        if (albedoAlpha > 0.1f)
                        {
                            finalhit = triHit;
                            finalhit.meshIndex = i;
                            finalhit.uvScale = currentUvScale;
                            finalhit.hitInstanceUUID = meshes[i].instanceUUID;
                            finalhit.colour = vec4(triangles[t].a.w, triangles[t].b.w, triangles[t].c.w, 1.0f);
                            mat3 nMat = mat3(currentNormalMatrix);
                            vec3 worldT = normalize(nMat * finalhit.T);
                            vec3 worldB = normalize(nMat * finalhit.B);
                            vec3 worldN = normalize(nMat * finalhit.lightNormal);

                            finalhit.TBN = mat3(worldT, worldB, worldN);
                        }
                }
            }
        }
        
        triOffset += meshes[i].triangleCount;
    }
    }

    return finalhit;
}

vec4 PointLight(vec3 hitpos, Light inputLight, float maxDist)
{
    hitResult finalhit; 
    finalhit.hit = false; 
    finalhit.hitDistance = maxDist; 

    // first step i think is to fetch distance to light
    float lightDistance = distance(hitpos, inputLight.position);
    // check if light distance is within range of the inputlight range
    if (lightDistance > inputLight.radius) {
        return vec4(0.0f);
    }
    // next step is to shoot a ray from the hitpos to the light position
    vec3 lightDir = normalize(inputLight.position - hitpos);
    // shoot ray towards light
    hitResult lightHit = BreadPhaseSceneTrace(hitpos + lightDir * 0.01f, lightDir, lightDistance - 0.02f);
    // if we hit something before the light, return 0
    // there will be hit distance, i think if we hit an object behind the lightdistance unblocked
    // so if hit distance is less than lightdistance - small epsilon, its blocked

    // if hit and distance of incident to hit is less than distance between hitpos and inputlight position
    if (lightHit.hit && lightHit.hitDistance < lightDistance) {
        return vec4(0.0f);
    }

    float attenuation = 1.0f - (lightDistance / inputLight.radius);
    vec3 lightContribution = inputLight.colour * attenuation;
    return vec4(lightContribution, 1.0f);
}

vec4 directLight(vec3 hitpos, vec3 direction, vec3 colour, float maxDist, vec3 normal)
{
    vec3 rayDir = normalize(direction);

    float dotNL = max(dot(normal, rayDir), 0.0f);
    if (dotNL <= 0.0f) return vec4(0.0f);


    // shoot ray towards light
    hitResult lightHit = BreadPhaseSceneTrace(hitpos + normal * 0.001f, rayDir, maxDist);
    // if we hit something, return 0
    if (lightHit.hit) {
        return vec4(0.0f);
    }
    // else return light colour
    return vec4(colour * dotNL, 1.0f);
}

vec4 lightstrace(vec3 hitpos,vec3 normal, float maxDist)
{
        float ambient = 0.0f;
            
        vec4 lightcolour = vec4(vec3(ambient),0.0f);

        if (lightCount > 0)
        {
            for (int i = 0; i < lightCount; i++)
            {
                vec3 L = normalize(Lights[i].position - hitpos);
                float dotNL = max(dot(normal, L), 0.0);
                if (Lights[i].type == 0) // spotlight
                {
                    // TODO
                }
                else if (Lights[i].type == 1) // point light
                {
                    vec4 pl = PointLight(hitpos, Lights[i], maxDist);
                    lightcolour.xyz += pl.xyz * dotNL;
                }
            }

        }

        if (doDirLight)
        {
            vec3 dirLightColour = vec3(1.0f, 1.0f, 1.0f) * 0.5f;
            vec4 dl = directLight(hitpos, directLightPos, directLightCol, maxDist, normal);
            lightcolour.xyz += dl.xyz;
        } 

    return lightcolour;
}

vec3 sampleHemisphere(vec3 normal)
{
    float u = rand(vec2(gl_GlobalInvocationID.xy) + time); 
    float v = rand(vec2(u, time));

    float phi = 2.0 * 3.14159265 * u;
    float cosTheta = sqrt(1.0 - v);
    float sinTheta = sqrt(v);

    vec3 localDir = vec3(cos(phi) * sinTheta, sin(phi) * sinTheta, cosTheta);

    vec3 helper = abs(normal.y) < 0.999 ? vec3(0, 1, 0) : vec3(1, 0, 0);
    vec3 tangent = normalize(cross(helper, normal));
    vec3 bitangent = cross(normal, tangent);

    return tangent * localDir.x + bitangent * localDir.y + normal * localDir.z;
}

vec3 indirectTrace(hitResult hit, vec3 incidentDir, vec3 hitColour, vec3 normal, int bounces, int samples, float maxDist)
{
    vec3 iColour = hitColour;
    vec3 currentOrigin = hit.lasthit;
    vec3 currentDir = incidentDir;
    vec3 currentLightNormal = normal;
    vec3 currentCollisionNormal = hit.normal; 

    float dim = 1.0f;

    for (int i = 0; i < bounces; i++)
    {
        for (int i = 0; i < samples; i++)
        {
            if (dim <= 0.0f) break;
            // calculate bounceDir off lightnormal

            // so this needs to be randomized in a sphere, and the samples will be okay because this is random
            vec3 bounceDir = sampleHemisphere(normalize(currentLightNormal));

            //if bounce dir points towards triangle, fallback to currentCollisionNormal
            if (dot(bounceDir, currentCollisionNormal) < 0.0f) {
               bounceDir = reflect(currentDir, currentCollisionNormal);
            }

            // offset collision normal
            vec3 offsetOrigin = currentOrigin + (currentCollisionNormal * 0.001f);

            hitResult res = BreadPhaseSceneTrace(offsetOrigin, bounceDir, maxDist);

            if (res.hit)
            {
                currentOrigin = res.lasthit;
                currentDir = bounceDir;
                currentCollisionNormal = res.normal;

                vec2 adjustedUV = res.uv * res.uvScale.xy;

                sampler2D albedoSampler = sampler2D(meshes[res.meshIndex].albedoHandle); 
                vec4 albedoColour = texture(albedoSampler, adjustedUV);

                vec3 specColour = vec3(0.0f, 0.0f, 0.0f);
                if (meshes[res.meshIndex].specularHandle != 0)
                {
                    sampler2D specularSampler = sampler2D(meshes[res.meshIndex].specularHandle); 
                    specColour = texture(specularSampler, adjustedUV).rgb;
                }

                vec3 normColour = vec3(0.0f, 0.0f, 0.0f);
                vec3 NormalMap = res.lightNormal; // light normal fallback
                if (meshes[res.meshIndex].normalHandle != 0)
                {
                    sampler2D normalSampler = sampler2D(meshes[res.meshIndex].normalHandle); 
                    normColour = texture(normalSampler, adjustedUV).rgb;
                    normColour = normColour * 2.0f - 1.0f;
                    NormalMap = normalize(res.TBN * normColour.rgb);
                }

                currentLightNormal = NormalMap;
                vec4 shadowcolour = lightstrace(currentOrigin,NormalMap, maxDist);

                iColour += (shadowcolour.rgb * albedoColour.rgb) * 0.5f * specColour.g * dim;
                dim *= 0.5f;
            }
            else {
                samplerCube sbSamp = samplerCube(skyboxHandle);

        	    vec3 sky = texture(sbSamp, bounceDir).rgb;
                iColour += sky * dim;
                break;
            }
        }

    }

    return iColour;
}

vec3 reflectionPass(hitResult hit, vec3 incidentDir, vec3 normal, vec3 initSpec, int bounces, float maxDist)
{
    vec3 reflectionColour = vec3(0.0f);
    vec3 currentOrigin = hit.lasthit;
    vec3 currentDir = incidentDir;
    vec3 currentLightNormal = normal;
    vec3 currentCollisionNormal = hit.normal; 
    
    float dim = 1.0f;

    for (int i = 0; i < bounces; i++)
    {
        if (dim <= 0.0f) break;

        // calculate bounceDir off lightnormal
        vec3 bounceDir = reflect(currentDir, normalize(currentLightNormal));

        //if bounce dir points towards triangle, fallback to currentCollisionNormal
        if (dot(bounceDir, currentCollisionNormal) < 0.0f) {
            bounceDir = reflect(currentDir, currentCollisionNormal);
        }

        // offset collision normal
        vec3 offsetOrigin = currentOrigin + (currentCollisionNormal * 0.001f);

        hitResult res = BreadPhaseSceneTrace(offsetOrigin, bounceDir, maxDist);

        if (res.hit)
        {
            currentOrigin = res.lasthit;
            currentDir = bounceDir;
            currentCollisionNormal = res.normal;

            vec2 adjustedUV = res.uv * res.uvScale.xy;

            vec4 albedoColour = vec4(0.0f);
            if (meshes[res.meshIndex].albedoHandle != 0)
            {
                sampler2D albedoSampler = sampler2D(meshes[res.meshIndex].albedoHandle); 
                albedoColour = texture(albedoSampler, adjustedUV);
            }
            vec3 specColour = vec3(0.0f, 0.0f, 0.0f);
            if (meshes[res.meshIndex].specularHandle != 0)
            {
                sampler2D specularSampler = sampler2D(meshes[res.meshIndex].specularHandle); 
                specColour = texture(specularSampler, adjustedUV).rgb;
            }
            if (specColour.g == 0.0f) break; 

            vec3 normColour = vec3(0.0f, 0.0f, 0.0f);
            vec3 NormalMap = res.lightNormal; // light normal fallback
            if (meshes[res.meshIndex].normalHandle != 0)
            {
                sampler2D normalSampler = sampler2D(meshes[res.meshIndex].normalHandle); 
                normColour = texture(normalSampler, adjustedUV).rgb;
                normColour = normColour * 2.0f - 1.0f;
                NormalMap = normalize(res.TBN * normColour.rgb);
            }

            currentLightNormal = NormalMap;
            vec4 shadowcolour = lightstrace(currentOrigin,NormalMap, maxDist);

            reflectionColour += (shadowcolour.rgb * albedoColour.rgb) * 0.5f * specColour.b * dim;
            dim *= 0.5f;
        }
        else {
            samplerCube sbSamp = samplerCube(skyboxHandle);

        	vec3 sky = texture(sbSamp, bounceDir).rgb;
            reflectionColour += sky * dim;
            break;
        }
    }

    return reflectionColour * initSpec.b;
}


vec3 reflectionIndirectPassBroad(hitResult hit, vec3 incidentDir, vec3 normal, vec3 initSpec, int bounces, float maxDist, int iBounces, int iSamples)
{
    vec3 iColour = vec3(0.0f);
    vec3 currentOrigin = hit.lasthit;
    vec3 currentDir = incidentDir;
    vec3 currentLightNormal = normal;
    vec3 currentCollisionNormal = hit.normal; 
    
    float dim = 1.0f;

    for (int i = 0; i < bounces; i++)
    {
        if (dim <= 0.0f) break;

        // calculate bounceDir off lightnormal
        vec3 bounceDir = reflect(currentDir, normalize(currentLightNormal));

        //if bounce dir points towards triangle, fallback to currentCollisionNormal
        if (dot(bounceDir, currentCollisionNormal) < 0.0f) {
            bounceDir = reflect(currentDir, currentCollisionNormal);
        }

        // offset collision normal
        vec3 offsetOrigin = currentOrigin + (currentCollisionNormal * 0.001f);

        hitResult res = BreadPhaseSceneTrace(offsetOrigin, bounceDir, maxDist);

        if (res.hit)
        {
            currentOrigin = res.lasthit;
            currentDir = bounceDir;
            currentCollisionNormal = res.normal;

            vec2 adjustedUV = res.uv * res.uvScale.xy;

            vec4 albedoColour = vec4(0.0f);
            if (meshes[res.meshIndex].albedoHandle != 0)
            {
                sampler2D albedoSampler = sampler2D(meshes[res.meshIndex].albedoHandle); 
                albedoColour = texture(albedoSampler, adjustedUV);
            }
            vec3 specColour = vec3(0.0f, 0.0f, 0.0f);
            if (meshes[res.meshIndex].specularHandle != 0)
            {
                sampler2D specularSampler = sampler2D(meshes[res.meshIndex].specularHandle); 
                specColour = texture(specularSampler, adjustedUV).rgb;
            }
            vec3 normColour = vec3(0.0f, 0.0f, 0.0f);
            vec3 NormalMap = res.lightNormal; // light normal fallback
            if (meshes[res.meshIndex].normalHandle != 0)
            {
                sampler2D normalSampler = sampler2D(meshes[res.meshIndex].normalHandle); 
                normColour = texture(normalSampler, adjustedUV).rgb;
                normColour = normColour * 2.0f - 1.0f;
                NormalMap = normalize(res.TBN * normColour.rgb);
            }
            currentLightNormal = NormalMap;
            vec4 shadowcolour = lightstrace(currentOrigin,NormalMap, maxDist);
            vec3 albedoDirect = shadowcolour.rgb * albedoColour.rgb;
            //iColour += (shadowcolour.rgb * albedoColour.rgb) * 0.5f * dim;
            vec3 indirectColour = indirectTrace(res, bounceDir, albedoDirect, NormalMap, iBounces, iSamples, maxDist);
            iColour += indirectColour * 0.5f * specColour.b * dim;
            dim *= 0.5f;
        }
        else {

            samplerCube sbSamp = samplerCube(skyboxHandle);
        	vec3 sky = texture(sbSamp, bounceDir).rgb;
            iColour += sky * dim;
            break;
        }
    }

    return iColour * initSpec.b;
}

void main() {
    // Intentionally does nothing
    const ivec2 pixelCoords = ivec2(gl_GlobalInvocationID.xy);

    ivec2 size = imageSize(outSignals).xy;
    // return if off screen
    if (pixelCoords.x >= size.x || pixelCoords.y >= size.y) return;
    vec4 noiseStatus = vec4(1.0, 1.0, 1.0, 1.0);

    int newFrameCount = frameCount;

    // clear image with bluish colour
    if (!doAccumulate) {
        storeSignal(SIGNAL_DIRECT, pixelCoords, vec4(0.0f, 0.0f, 0.0f, 1.0f)); // diffuse
        storeSignal(SIGNAL_INDIRECT, pixelCoords, vec4(0.0f, 0.0f, 0.0f, 1.0f)); // indirect
        storeSignal(SIGNAL_SPECULAR, pixelCoords, vec4(0.0f, 0.0f, 0.0f, 1.0f)); // spec
        storeSignal(SIGNAL_SPEC_IND, pixelCoords, vec4(0.0f, 0.0f, 0.0f, 1.0f)); // specind
        storeSignal(SIGNAL_EMISSION, pixelCoords, vec4(0.0f, 0.0f, 0.0f, 1.0f)); // em
        storeSignal(SIGNAL_NOISE, pixelCoords, noiseStatus); // noise
        newFrameCount = 1;
    }

    //if (depthDist >= maxDistance)
    //{
    //    imageStore(screen, pixelCoords, vec4(skycolour, 0.0f));
    //    return;
    //}

    bool primaryskip = false;
    bool indirectskip = false;
    // if pixel already exisits skip
    vec4 existingColor = loadSingal(SIGNAL_NOISE, pixelCoords);
    if (existingColor.r < 1.0f) {primaryskip = true;}

    if (newFrameCount > MaxAccumulatedFrames && MaxAccumulatedFrames != 0) indirectskip = true;

    if (primaryskip && indirectskip) return;

    if (!primaryskip) storeSignal(SIGNAL_NOISE, pixelCoords, noiseStatus);

    vec2 noiseUV = vec2(gl_GlobalInvocationID.xy) / vec2(textureSize(BlueNoiseTex, 0));
    float noiseVal = texture(BlueNoiseTex, noiseUV).r;

    float finalNoise = fract(noiseVal * time);
    //noise
    if (finalNoise > noiseThreshold) {    if (!primaryskip){ storeSignal(SIGNAL_NOISE, pixelCoords, noiseStatus);} return;}
    else {noiseStatus = vec4(0.0, 0.0, 0.0, 1.0);}
    
    // camera matrix
    mat4 invProj = inverse(u_ProjectionMatrix); mat4 invView = inverse(u_ViewMatrix);

    vec3 rayDir = rayDirfromCam(invProj, invView, pixelCoords, size);

    if (!primaryskip){

    samplerCube sbSamp = samplerCube(skyboxHandle);

    vec3 sky = texture(sbSamp, rayDir).rgb;

    storeSignal(SIGNAL_DIRECT, pixelCoords, vec4(sky, 1.0f)); // direct
    storeSignal(SIGNAL_NOISE, pixelCoords, noiseStatus); // noise
    }

    const ivec2 depthsize = textureSize(depthMap, 0);

    vec2 depthUV = vec2(pixelCoords) / vec2(size);

    float gDepth = texture(depthMap, depthUV).r;

    float depthDist = linearizeDepth(gDepth, 0.1f, maxDistance);

    //return;
    
    if (depthDist >= maxDistance) return;

    // create tex for 4 signals
    vec3 directColour = vec3(0.0f);
    vec3 indirectColour = vec3(0.0f);
    vec3 specularColour = vec3(0.0f);
    vec3 specularIndirectColour = vec3(0.0f);
    vec3 emissionColour = vec3(0.0f);
    // reflectionIndirectPassBroad
    hitResult firstHit = BreadPhaseSceneTrace(cameraPosition, rayDir, maxDistance);
    if (firstHit.hit)
    {
        vec2 adjustedUV = firstHit.uv * firstHit.uvScale.xy;
        //firstHit.uv;
        vec4 albedoColour = vec4(0.0f);
        if (meshes[firstHit.meshIndex].albedoHandle != 0)
        {
            sampler2D albedoSampler = sampler2D(meshes[firstHit.meshIndex].albedoHandle); 
            albedoColour = texture(albedoSampler, adjustedUV); // uvScale
        }
        vec4 albedo = albedoColour;
        albedo.a = 1.0f;

        vec4 specColour = vec4(0.0f, 0.0f, 0.0f, 1.0f);
        if (meshes[firstHit.meshIndex].specularHandle != 0)
        {
            sampler2D specularSampler = sampler2D(meshes[firstHit.meshIndex].specularHandle); 
            specColour = texture(specularSampler, adjustedUV);
        }
        vec3 normColour = vec3(0.0f, 0.0f, 0.0f);
        vec3 NormalMap = firstHit.lightNormal; // light normal fallback
        if (meshes[firstHit.meshIndex].normalHandle != 0)
        {
            sampler2D normalSampler = sampler2D(meshes[firstHit.meshIndex].normalHandle); 
            normColour = texture(normalSampler, adjustedUV).rgb;
            normColour = normColour * 2.0f - 1.0f;
            NormalMap = normalize(firstHit.TBN * normColour.rgb);
        }

        // g = roughness
        // b = metalic

        vec3 offsetPos = firstHit.lasthit + (firstHit.lightNormal * 0.001f);
        if (!primaryskip || !indirectskip) directColour = lightstrace(offsetPos, NormalMap, maxDistance).xyz; // indirect
        if (reflectionBounces > 0 && !primaryskip) 
            specularColour = reflectionPass(firstHit, rayDir, NormalMap, specColour.rgb, reflectionBounces, reflectionDistance);

        if (indirectBounces > 0 && indirectSamples > 0 && !indirectskip)
        {
            indirectColour = indirectTrace(firstHit, rayDir, albedo.rgb * directColour, NormalMap,
            indirectBounces, indirectSamples, reflectionDistance); // bounces then samples
        
            if (reflectionBounces > 0){
                specularIndirectColour = reflectionIndirectPassBroad(firstHit, rayDir, NormalMap, specColour.rgb, reflectionBounces,
                reflectionDistance, indirectBounces, indirectSamples);
            }


        }
        emissionColour = vec3(0.0f); // for now

    }

    // noise
    storeSignal(SIGNAL_NOISE, pixelCoords, noiseStatus);


    if (!primaryskip)
    {
        // direct and specular
        storeSignal(SIGNAL_DIRECT, pixelCoords, vec4(directColour, 1.0f));
        storeSignal(SIGNAL_SPECULAR, pixelCoords, vec4(specularColour, 1.0f));
    }

    if (!indirectskip)
    {
        // indirect
        vec4 oldIndirect = loadSingal(SIGNAL_INDIRECT, pixelCoords);
        vec4 newIndirect = vec4(indirectColour, 1.0f); 
        vec4 IDaccum = oldIndirect + (newIndirect - oldIndirect) / float(newFrameCount);

        // specular indirect
        vec4 oldSpecularIndirect = loadSingal(SIGNAL_SPEC_IND, pixelCoords);
        vec4 newSpecularIndirect = vec4(specularIndirectColour, 1.0f); 
        vec4 ISDaccum = oldSpecularIndirect + (newSpecularIndirect - oldSpecularIndirect) / float(newFrameCount);

        // emission
        vec4 oldEm = loadSingal(SIGNAL_EMISSION, pixelCoords);
        vec4 newEm = vec4(emissionColour, 1.0f); 
        vec4 Eaccum = oldEm + (newEm - oldEm) / float(newFrameCount);

        storeSignal(SIGNAL_INDIRECT, pixelCoords, IDaccum);
        storeSignal(SIGNAL_SPEC_IND, pixelCoords, ISDaccum);
        storeSignal(SIGNAL_EMISSION, pixelCoords, Eaccum);
    }
} // closer

    // direct /0
    // indirect /1
    // specular /2 
    // specularIndirect /3
    // emission /4
    // noise mask /5