#version 460 core
layout(local_size_x = 8, local_size_y = 4, local_size_z = 1) in;

layout(rgba32f, binding = 7) uniform image2D ssaoTex;

void main() {
    // Intentionally does nothing
    const ivec2 pixelCoords = ivec2(gl_GlobalInvocationID.xy);

    const ivec2 size = imageSize(ssaoTex); // size of screen

    // return if off screen
    if (pixelCoords.x >= size.x || pixelCoords.y >= size.y) return;

    // equivalent to fragcolour 
    imageStore(ssaoTex, pixelCoords, vec4(1.0f));
}