#version 460 core
layout(local_size_x = 8, local_size_y = 4, local_size_z = 1) in;

layout(rgba32f, binding = 0) uniform image2D screen;

// uniforms

uniform mat4 u_ViewMatrix;
uniform mat4 u_ProjectionMatrix;
uniform vec3 cameraPosition;
uniform float time;
uniform float deltatime;

void main() {
    // Intentionally does nothing
    const ivec2 pixelCoords = ivec2(gl_GlobalInvocationID.xy);

    const ivec2 size = imageSize(screen); // size of screen

    
    imageStore(screen, pixelCoords, vec4(0.0f, 0.0f, 0.0f, 0.0f));

    // return if off screen
    if (pixelCoords.x >= size.x || pixelCoords.y >= size.y) return;


    // ray direction
    vec2 uv = vec2(pixelCoords / vec2 (size) * 2.0 - 1.0);

    // camera matrix
    mat4 invProj = inverse(u_ProjectionMatrix);
    mat4 invView = inverse(u_ViewMatrix);

    vec4 target = invProj * vec4(uv.x, uv.y, 1.0, 1.0);

    vec3 rayDirWorld = vec3(invView * vec4(normalize(target.xyz), 0.0));
    vec3 rayDir = normalize(rayDirWorld);

    // equivalent to fragcolour 
    imageStore(screen, pixelCoords, vec4(rayDir, 1.0));
}