#version 460 core

#extension GL_ARB_gpu_shader_int64 : enable
#extension GL_ARB_bindless_texture : require

#define INF 3.40282347e+38f

layout(local_size_x = 8, local_size_y = 8, local_size_z =8) in;

layout(rgba16f, binding = 0) uniform image3D outIndirect;
layout(rgba16f, binding = 1) uniform image3D outEmission;

uniform float time;
uniform int frame;
uniform vec3 directLightPos;
uniform vec3 directLightCol;
uniform bool doDirLight;
uniform float directAmbient;
uniform mat4 lightProjection;
uniform float dirSpecularLight;
uniform bool doDirSpecularLight;
uniform samplerCube cmMainHandle;
uniform sampler2DShadow  shadowMap;
uniform int FilterRadius;
uniform int NumberOfSamples;
uniform float DirSMMaxBias;
uniform bool doDirShadowMap;
uniform vec3 sceneBoundPos;
uniform vec3 sceneBoundScale;


// temporary
uniform vec3 ivPosition;
uniform float ivScale;
uniform bool ivDirty;
uniform ivec3 volumeSize;

struct Light{
    vec3 position;
    vec3 rotation;
    vec3 colour;
    float radius;
    int type;
};
// i seriously need a light ssbo....
uniform Light Lights[64];
uniform int lightCount;
// temp fields 

struct MDF{
    vec4 position;  // uv.x
    vec4 extents;  // uv.y
    vec4 rootPosition;
    vec4 rootExtents;
    vec4 gPosition;
    vec4 gExtents;
//vec4 gRotation;
    mat4 globalTransform;

    uint64_t instanceUUID;
    sampler3D SDF_Handle;

    sampler2D texture_diffuse_Handle;
    sampler2D texture_roughness_Handle;
    sampler2D texture_normal_Handle;
    sampler2D texture_emission_Handle;

};
// mesh distance fields
layout(std430, binding = 11) buffer MDF_Buffer {
    MDF MDFS[];
};
float mindist = 0.01f;
float i_maxdist = 64.0f;
int i_steps = 80;
int i_minLodLevel = 10;
float i_noiseThreshold  = 1.0;
int i_coneSteps = 32;
float i_coneApature =0.05;  // 0.1 originally but 0.05 brings simular quality to rm
bool i_doConeTracing = false;
float i_indirectBoost = 3.0f; // default at 1.0
float e_emissionBoost = 1.0f; // default at 1.0
int angles = 360;
int maxlodLevel = 0; // off
float transitionRangeLOD = 10.0f;
//int SDFtextureLodLevel = 0;
float maxSDFDist = 128.0f;
float blendrate =  0.95;

struct hitresult{
    vec3 normal;
    vec3 hitpos;
    vec2 uv;
//float totalDistanceTravelled;
    float distance;
    float maxDist;
    float iterationsDBG;
//float lowestDistance;
    int materialIndex;
    bool isHit;
};


float sdBox(vec3 p, vec3 b){
    vec3 q = abs(p) - b;
    return length(max(q, 0.0)) + min(max(q.x, max(q.y, q.z)), 0.0f);
}

float fOpUnionID(float res1, float res2){
    return (res1 < res2) ? res1 : res2;
}
vec4 fOpUnionID4(vec4 res1, vec4 res2){
    return (res1.x < res2.x) ? res1 : res2;
}

vec3 transformP(vec3 p, mat4 matrix){
    vec4 np = matrix * vec4(p, 1.0);
    return np.xyz;
}

float texture3DSDF(vec3 p, vec3 s, sampler3D handle, int lodLevel){
    vec3 distance = abs(p) - s;

    float outsideDistance = length(max(distance, 0.0));

    // map coords to 3d uv space
    vec3 uvw = (p / (s* 2.0)) + 0.5;

    float SDF = textureLod(handle, uvw, lodLevel).r;

    if (outsideDistance > 0.0) return SDF + outsideDistance;

    return SDF;
}


vec3 texture3DSDFUV(vec3 p, vec3 s, sampler3D handle, int lodLevel){
    vec3 distance = abs(p) - s;

    float outsideDistance = length(max(distance, 0.0));

    // map coords to 3d uv space
    vec3 uvw = (p / (s* 2.0)) + 0.5;

    vec3 SDF = textureLod(handle, uvw, lodLevel).rgb;

    if (outsideDistance > 0.0) return vec3(SDF.r + outsideDistance, SDF.yz);

    return SDF;
}

vec3 nearestPointOnAABB(vec3 p, vec3 pos, const vec3 extents){
    return clamp(p, pos - extents, pos + extents);
}

int calculateLODLevel(vec3 vPosition, vec3 cameraPosition, float transitionDistance, int maxLOD){
    float distance = distance(vPosition, cameraPosition);
    int targetLOD = int(distance / transitionDistance);
    targetLOD = min(targetLOD, maxLOD);

    return targetLOD;
}

vec4 SDFMesh(vec3 p, int index, int lodLevel){
    vec3 gp = p - MDFS[index].gPosition.xyz;
    vec3 fp = transformP(gp, MDFS[index].globalTransform);

    vec3 nsdfv = texture3DSDFUV(fp, MDFS[index].gExtents.rgb, MDFS[index].SDF_Handle, lodLevel);

    vec2 uv = nsdfv.gb * vec2(MDFS[index].position.w, MDFS[index].extents.w);

    return vec4(nsdfv.r, float(index), uv);
}

float SDFMeshDist(vec3 p, int index, int lodLevel){
    vec3 gp = p - MDFS[index].gPosition.xyz;
    vec3 fp = transformP(gp, MDFS[index].globalTransform);

    float nsdfv = texture3DSDFUV(fp, MDFS[index].gExtents.rgb, MDFS[index].SDF_Handle, lodLevel).r;

    return nsdfv;
}

// moved up here since its in the way
hitresult aabbVsRay(vec3 ro, vec3 rd, vec3 p, vec3 s){
    hitresult hr; hr.isHit = false; hr.distance = INF;
    vec3 Min = p - s;
    vec3 Max = p + s;

    vec3 invRD = 1.0f / rd;

    vec3 t0 = (Min - ro) * invRD;
    vec3 t1 = (Max - ro) * invRD;

    vec3 tMin = min(t0, t1);
    vec3 tMax = max(t0, t1);

    float tNear = max(max(tMin.x, tMin.y), tMin.z);
    float tFar = min(min(tMax.x, tMax.y), tMax.z);

    if (tNear > tFar || tFar < 0) { return hr; }

    hr.isHit = true;
    hr.distance = tNear;
    hr.maxDist = tFar;
    return hr;
}


vec4 sceneSDFIndex(vec3 p, int i, vec3 wp){ // scene
    vec4 tsdf = vec4(INF, 0.0, 0.0, 0.0);

    //aabbHitDBGmode
    //index
    //if (sdBox(p - sceneBoundPos.xyz, sceneBoundScale.xyz) > tsdf.x) return tsdf;

    vec3 np = nearestPointOnAABB(wp, MDFS[i].rootPosition.xyz, MDFS[i].rootExtents.xyz);

    if (distance(np, wp) > maxSDFDist) return vec4(INF, 0.0, 0.0, 0.0);

    float root = sdBox(p - MDFS[i].rootPosition.xyz, MDFS[i].rootExtents.xyz);
    if (root < tsdf.x){

        int lodLevel = calculateLODLevel(np, wp, transitionRangeLOD, maxlodLevel);
        vec4 sdfm = SDFMesh(p, i, lodLevel);
        //vec4 sdfm = vec4(root, 0.0, 0.0, 0.0);
        tsdf = sdfm;
    }
    return vec4(tsdf);
}

float sceneSDFdistIndex(vec3 p, int i, vec3 wp){ // scene
    float tsdf = INF;

    //if (sdBox(p - sceneBoundPos.xyz, sceneBoundScale.xyz) > tsdf) return tsdf;

    vec3 np = nearestPointOnAABB(wp, MDFS[i].rootPosition.xyz, MDFS[i].rootExtents.xyz);

    if (distance(np, wp) > maxSDFDist) return INF;

    float root = sdBox(p - MDFS[i].rootPosition.xyz, MDFS[i].rootExtents.xyz);
    if (root < tsdf){

        int lodLevel = calculateLODLevel(np, wp, transitionRangeLOD, maxlodLevel);
        float sdfm = SDFMeshDist(p, i, lodLevel);

        tsdf = sdfm;

    }
    return tsdf;
}


vec4 sceneSDF(vec3 p, vec3 wp ){ // scene
    vec4 tsdf = vec4(INF, 0.0, 0.0, 0.0);

    //aabbHitDBGmode

    if (sdBox(p - sceneBoundPos.xyz, sceneBoundScale.xyz) > tsdf.x) return vec4(INF, 0.0, 0.0, 0.0);

    for (int i = 0; i < MDFS.length(); i++ ){
        vec3 np = nearestPointOnAABB(wp, MDFS[i].rootPosition.xyz, MDFS[i].rootExtents.xyz);

        if (distance(np, wp) > maxSDFDist) continue;

        float root = sdBox(p - MDFS[i].rootPosition.xyz, MDFS[i].rootExtents.xyz);
        if (root < tsdf.x){

            int lodLevel = calculateLODLevel(np, wp, transitionRangeLOD, maxlodLevel);
            vec4 sdfm = SDFMesh(p, i, lodLevel);
            //vec4 sdfm = vec4(root, 0.0, 0.0, 0.0);

            if (i == 0) {
                tsdf = sdfm;
                continue;
            }
            tsdf = fOpUnionID4(tsdf,sdfm); //fOpUnionRoundID4 fOpUnionID4
        }
    }
    return vec4(tsdf);
}

vec3 CalculateNormalInd( in vec3 p, int index, vec3 wp){
    const float eps = 0.01;
    const vec2 h = vec2(eps,0);
    return normalize( vec3(sceneSDFdistIndex(p+h.xyy, index, wp) - sceneSDFdistIndex(p-h.xyy, index, wp),
            sceneSDFdistIndex(p+h.yxy, index, wp) - sceneSDFdistIndex(p-h.yxy, index, wp),
            sceneSDFdistIndex(p+h.yyx, index, wp) - sceneSDFdistIndex(p-h.yyx, index, wp) ) );
}


hitresult RayAcceleratedSphereMarchScene(vec3 ro, vec3 rd, float maxdist, float mindist, int steps, int index, vec3 wp){
    hitresult hr;
    hr.isHit = false;
    hr.distance = INF;
    //hr.lowestDistance = INF;
    float t = 0.0; // total distance travelled

    // raymarching
    for (int i = 0; i < steps; i++){
        vec3 pos = ro + rd* t;// position along the ray
        
        float dist = sceneSDFdistIndex(pos, index, wp);

        //if (hr.lowestDistance > dist) hr.lowestDistance = dist;

        if (dist < mindist){ // treat as if hit
            vec4 m = sceneSDFIndex(pos, index, wp);
            hr.isHit = true;
            hr.distance = dist;
            //hr.totalDistanceTravelled = t;
            hr.normal = CalculateNormalInd(pos, index, wp);
            hr.materialIndex = int(m.y);
            hr.hitpos = pos;
            hr.uv = m.zw;
            hr.iterationsDBG = float(i) / float(steps);

            break;// how small dist (radius around march)
        }
        t += dist;

        if (t > maxdist) break; // failed to hit
        //discard; // discard on far for transparency
        // how large dist (radius around march)
    }

    return hr;
}

hitresult raytraceRootHitST(vec3 ro, vec3 rd, float maxdist, float mindist, int steps, vec3 wp){
    hitresult hr; hr.isHit = false; hr.distance = INF;

    //return raymarchScene(ro, rd, maxdist, mindist, steps);

    for (int i = 0; i < MDFS.length(); i++ ){
        hitresult aabbHR = aabbVsRay(ro, rd, MDFS[i].rootPosition.xyz, MDFS[i].rootExtents.xyz);

        if (!aabbHR.isHit) continue;
        float sd = max(0.0, aabbHR.distance);
        if (sd >= hr.distance)  continue;

        float elipson = (sd + 0.001f);
        vec3 pokePoint = ro + rd * elipson;

        float lMaxDist = min(maxdist - elipson, hr.distance - elipson);
        if (lMaxDist <= 0.0) continue;

        hitresult rmHR = RayAcceleratedSphereMarchScene(pokePoint, rd, lMaxDist, mindist, steps, i, wp);

        if (rmHR.isHit){
            float tHitDist = elipson + rmHR.distance;
            if (tHitDist < hr.distance) {
                hr = rmHR;
                hr.distance =tHitDist;
                hr.hitpos = ro + rd * tHitDist;
            }
        }
    }
    return hr;
}

hitresult RayAcceleratedConeTraceScene(vec3 ro, vec3 rd, float maxdist, int steps, float aperture,  int index, vec3 wp){
    hitresult hr;
    hr.isHit = false;
    hr.distance = INF;
    float t = 0.0; // total distance travelled

    // raymarching
    for (int i = 0; i < steps; i++){
        vec3 pos = ro + rd* t;// position along the ray

        float dist = sceneSDFdistIndex(pos, index, wp);

        float radius = t * aperture;

        //radius += radius * aperture; // add by current radius * the aperture
        //if (hr.lowestDistance > dist) hr.lowestDistance = dist;

        if (dist < radius){ // treat as if hit
            vec4 m = sceneSDFIndex(pos, index, wp);
            hr.isHit = true;
            hr.distance = dist;
            //hr.totalDistanceTravelled = t;
            hr.normal = CalculateNormalInd(pos, index, wp);
            hr.materialIndex = int(m.y);
            hr.iterationsDBG = float(i) / float(steps);
            hr.hitpos = pos;
            hr.uv = m.zw;

            break;// how small dist (radius around march)
        }
        t += max(dist, radius);

        if (dist > maxdist) break; // failed to hit

    }

    return hr;
}

hitresult raytraceRootHitCT(vec3 ro, vec3 rd, float maxdist, int steps, float apature, vec3 wp){
    hitresult hr; hr.isHit = false; hr.distance = INF;

    //return raymarchScene(ro, rd, maxdist, mindist, steps);

    for (int i = 0; i < MDFS.length(); i++ ){
        hitresult aabbHR = aabbVsRay(ro, rd, MDFS[i].rootPosition.xyz, MDFS[i].rootExtents.xyz);

        if (!aabbHR.isHit) continue;
        float sd = max(0.0, aabbHR.distance);
        if (sd >= hr.distance)  continue;

        float elipson = (sd + 0.001f);
        vec3 pokePoint = ro + rd * elipson;

        float lMaxDist = min(maxdist - elipson, hr.distance - elipson);
        if (lMaxDist <= 0.0) continue;

        hitresult rmHR = RayAcceleratedConeTraceScene(pokePoint, rd, lMaxDist, steps, apature, i, wp);

        if (rmHR.isHit){
            float tHitDist = elipson + rmHR.distance;
            if (tHitDist < hr.distance) {
                hr = rmHR;
                hr.distance =tHitDist;
                hr.hitpos = ro + rd * tHitDist;
            }
        }
    }
    return hr;
}



float CalcShadowFactorDIR(vec4 LightSpacePos, vec3 lightDirection, vec3 normal, vec3 iPosition){
    // perform perspective divide
    vec3 lightCoords = LightSpacePos.xyz / LightSpacePos.w;
    float shadow = 0.0f;

    // shadow calculation
    if (lightCoords.z <= 1.0f){
        lightCoords = (lightCoords + 1.0f) / 2.0f;
        // get the current depth
        float currentDepth = lightCoords.z;
        // calculate shadow bias
        float bias = max(DirSMMaxBias * (1.0f - dot(normal, lightDirection)), 0.0005f);
        // PCF
        int sampleRadius = FilterRadius; // FilterRadius // NumberOfSamples
        //vec2 texSize = vec2(textureSize(bluemap, 0));
        // uv
        //vec2 offset = vec2(fract(frame * 0.618), fract(frame * 0.133));
        //vec2 noiseUV = (texcoord / texSize) + offset;

        vec2 pixelSize = 1.0 / textureSize(shadowMap, 0);
        float tsamples = 0.0;
        for(int y = -sampleRadius; y <= sampleRadius; y++){
            for(int x = -sampleRadius; x <= sampleRadius; x++){
                //float angle = texture(bluemap, noiseUV).r * NumberOfSamples;
                //vec2 foffset = vec2(cos(angle), sin(angle));
                float closestDepth = texture(shadowMap, vec3(lightCoords.xy + (vec2(x, y)) * pixelSize, currentDepth - bias )).r;
                //if (currentDepth > closestDepth + bias)
                shadow += (1.0f - closestDepth);
                tsamples += 1.0f;

            }
        }

        shadow /= tsamples;
    }

    return shadow;
}


vec4 direcLight(vec3 ARM, vec3 iNormal, vec3 iPosition, vec3 wp){ // normals need to be recalculated based on rotation
    // shadow map 
    float shadow = 0.0f;

    vec3 normal = normalize(iNormal);

    vec3 lightDirection = normalize(directLightPos); //vec3(1.0f, 1.0f, 0.0f)
    float diffuse = max(dot(normal, lightDirection), 0.0f);

    vec4 fragPosLight = lightProjection * vec4(iPosition, 1.0f);

    float smShadow = 0.0;
    //float rmShadow = 0.0f;
    bool hit = false; // will be set to false inside ssshadow;
    
    if (doDirShadowMap && !hit) shadow = CalcShadowFactorDIR(fragPosLight, lightDirection, normal, iPosition);


    return ((diffuse * (1.0f - shadow) + directAmbient)) * vec4(directLightCol, 1.0f);
}


vec4 spotLight(int iteration, vec3 ARM, vec3 iNormal, vec3 iPosition, vec3 wp){
    // controls how big the area that is lit up is
    float outerCone = 0.90f;
    float innerCone = 0.95f;

    // ambient lighting
    //float ambient = 0.0f;

    // diffuse lighting
    vec3 normal = normalize(iNormal);

    vec3 lightDirection = normalize(Lights[iteration].position - iPosition);
    float diffuse = max(dot(normal, lightDirection), 0.0f);

    // calculates the intensity of the crntPos based on its angle to the center of the light cone
    float angle = dot(Lights[iteration].rotation, -lightDirection); // direction
    float inten = clamp( (angle - outerCone) / (innerCone - outerCone), 0.0f, 1.0);

    //float ssShadow = shadowTrace(lightDirection, normal, iPosition);

    float shadow = 0.0;
    return ((diffuse * (1.0f - shadow) * inten + 0.0f) * vec4(Lights[iteration].colour, 1.0) * inten);
}

vec4 pointLight(int iteration, vec3 ARM, vec3 iNormal, vec3 iPosition, vec3 wp){
    //vec3 lightVec = (Lights[iteration].position) - crntPos;
    vec3 lightVec = (Lights[iteration].position) - iPosition;

    // intensity of light with respect to distance
    float dist = length(lightVec);
    float a = 3.00f;
    float b = 0.70f;
    float inten = 1.0f / (a * dist * dist + b * dist + 1.0) * Lights[iteration].radius;

    // ambient lighting
    //float ambient = 0.0f;
    vec3 normal = normalize(iNormal);
    //vec3 normal = normalize(Normal); 

    vec3 lightDirection = normalize(lightVec);
    float diffuse = max(dot(normal, lightDirection), 0.0f);
    
    float shadow = 0.0;
    return ( (diffuse * (1.0f - shadow) * inten + 0.0f) * vec4(Lights[iteration].colour, 1.0) * inten);
}

vec4 lights(vec3 ARM, vec3 iNormal, vec3 iPosition, vec3 wp){
    vec4 colour = vec4(0.0);

    int maxLights = 64;
    for (int i = 0; i < min(lightCount, maxLights); i++){
        if (Lights[i].type == 0){
            colour += spotLight(i, ARM, iNormal, iPosition, wp);
        }

        if (Lights[i].type == 1){
            colour += pointLight(i, ARM, iNormal, iPosition, wp);
        }
    }

    if (doDirLight){
        colour+= direcLight(ARM, iNormal, iPosition, wp);
    }

    return colour;
}

float rand(vec2 co){
    return fract(sin(dot(co.xy ,vec2(12.9898, 78.233))) * 43758.5453);
}

vec3 fibonacciSphere(float i, float n){
    const float PHI = 1.61803398875;
    float y = 1.0 - (i / (n -1.0)) * 2.0f;
    float radius = sqrt(max(0.0, 1.0 - y * y));
    float theta = 2.0* 3.14159265 * i / PHI;
    
    float x = cos(theta) * radius;
    float z = sin(theta) * radius;
    
    return vec3(x,y,z);
}

vec3 fibonacciSphereJitter(float i, float n, float time){
    const float PHI = 1.61803398875;
    float y = 1.0 - (i / (n -1.0)) * 2.0f;
    float radius = sqrt(max(0.0, 1.0 - y * y));
    float theta = (2.0* 3.14159265 * i / PHI) + (time * 6.2831853);

    float x = cos(theta) * radius;
    float z = sin(theta) * radius;

    return vec3(x,y,z);
}

void indirectMarch(vec3 nrm, vec3 ro, float mindist, vec3 wp, out vec3 ind, out vec3 em){
    hitresult hr;
    if (!i_doConeTracing) hr = raytraceRootHitST(ro, nrm, i_maxdist, mindist, i_steps, wp);
    else hr = raytraceRootHitCT(ro, nrm, i_maxdist, i_coneSteps, i_coneApature, wp);

    if (!hr.isHit){
        ind = textureLod(cmMainHandle, nrm, 5).rgb;
        em = vec3(0.0f);
        return;
    }
    
    vec3 arm = textureLod( MDFS[hr.materialIndex].texture_roughness_Handle, hr.uv, i_minLodLevel).rgb;
    vec3 mcolour = textureLod(MDFS[hr.materialIndex].texture_diffuse_Handle, hr.uv, i_minLodLevel).rgb;
    vec3 shadow = lights(arm, hr.normal, hr.hitpos, wp).rgb;
    shadow += directAmbient;
    shadow = clamp(shadow, 0.0, 1.0);

    vec3 diffuseComponent = mcolour * shadow;
    ind = diffuseComponent;
    em = textureLod(MDFS[hr.materialIndex].texture_emission_Handle, hr.uv, i_minLodLevel).rgb;
}

float lumaFromRGB(vec3 rgb){
    vec3 weights = vec3(0.2126, 0.7152, 0.0722);
    float luminance = dot(rgb, weights);
    return luminance;
}

float RingTracePointScene(vec3 ro, float maxdist, int steps, float aperture){
    float distance = maxdist;
    //hr.lowestDistance = INF;
    float t = 0.0; // total distance travelled

    // raymarching
    for (int i = 0; i < steps; i++){
        vec4 m = sceneSDF(ro, ro);
        float dist = m.x;

        float radius = t * aperture;

        if (dist < radius){ // treat as if hit
            distance = dist;
            break;// how small dist (radius around march)
        }
        if (dist > maxdist) break; // failed to hit

        t += max(dist, radius);
    }

    return distance;
}

void main() {
    const ivec3 uvw = ivec3(gl_GlobalInvocationID.xyz);
    
    if (uvw.x >= volumeSize.x ||
        uvw.y >= volumeSize.y ||
        uvw.z >= volumeSize.z) return;
    
    vec3 normalizedUVW = (vec3(uvw) + vec3(0.5f)) / vec3(volumeSize);
    //vec3 normalizedUVW = (vec3(uvw)) / vec3(volumeSize);
    //vec3 localPos = normalizedUVW;
    vec3 localPos = normalizedUVW - vec3(0.5f);
    vec3 wp = ivPosition + (localPos * ivScale);
    float visability = RingTracePointScene(wp, 32, 32, 0.1);
    
    // distance search i should do and push into a
    if (visability < 0.01){
        //imageStore(outIndirect, uvw, vec4(vec3(1.0, 0.0, 0.0), visability));
        imageStore(outIndirect, uvw, vec4(vec3(0.0, 0.0, 0.0), visability));
        imageStore(outEmission, uvw, vec4(vec3(0.0, 0.0, 0.0), visability));
        return;
    }
    vec3 indirectLighting = vec3(0.0f);
    vec3 emissionLighting = vec3(0.0f);
    
    for (int i = 0; i < angles; i++){
        //vec3 dir = sampleSphere(uvw.xy + uvw.z, time);
        vec3 dir = fibonacciSphereJitter(float(i), angles, time);
        //vec3 dir = fibonacciSphereJitter(float(i), angles, frame);
        //vec3 dir = fibonacciSphere(float(i), angles);
        
        vec3 em = vec3(0.0); vec3 ind = vec3(0.0);

        indirectMarch(dir, wp, mindist, wp, ind, em);

        indirectLighting += ind;
        emissionLighting += em;
    }
    vec3 ind = vec3(indirectLighting / angles) * i_indirectBoost;
    vec3 em = vec3(emissionLighting / angles) * e_emissionBoost; // neds e boost
    
    vec3 priorIndirectData = vec3(0.0); vec3 priorEmissionData = vec3(0.0);
    if (!ivDirty){ 
        priorIndirectData = imageLoad(outIndirect, uvw).rgb;
        priorEmissionData = imageLoad(outEmission, uvw).rgb;
    }
    
    vec3 accumulatedIndirectData = mix(ind, priorIndirectData, blendrate);
    vec3 accumulatedEmissionData = mix(em, priorEmissionData, blendrate);
    
    imageStore(outIndirect, uvw, vec4(accumulatedIndirectData, visability));
    imageStore(outEmission, uvw, vec4(accumulatedEmissionData, visability));
}